export const ActionTypes = {
    'DEMO_ACTION_REQ': 'DEMO_ACTION_REQ',
    'DEMO_ACTION_RES': 'DEMO_ACTION_RES',

    'GET_SEARCH_USER_ID': 'GET_SEARCH_USER_ID',

    'GET_CUSTOMER_PROFILE_DATA_REQ': 'GET_CUSTOMER_PROFILE_DATA_REQ',
    'GET_CUSTOMER_PROFILE_DATA_RES': 'GET_CUSTOMER_PROFILE_DATA_RES',

    'GET_PLAN_DATA_REQ': 'GET_PLAN_DATA_REQ',
    'GET_PLAN_DATA_RES': 'GET_PLAN_DATA_RES',

    'GET_CHART_DATA_REQ': 'GET_CHART_DATA_REQ',
    'GET_CHART_DATA_RES': 'GET_CHART_DATA_RES',

    'GET_FAMILY_DATA_REQ': 'GET_FAMILY_DATA_REQ',
    'GET_FAMILY_DATA_RES': 'GET_FAMILY_DATA_RES',

    'GET_TRANSACTION_DATA_REQ': 'GET_TRANSACTION_DATA_REQ',
    'GET_TRANSACTION_DATA_RES': 'GET_TRANSACTION_DATA_RES',

    'GET_BILLING_TRANSACTION_DATA_RES': 'GET_BILLING_TRANSACTION_DATA_RES',
    'GET_ORDER_TRANSACTION_DATA_RES': 'GET_ORDER_TRANSACTION_DATA_RES',
    'GET_SERVICE_TRANSACTION_DATA_RES': 'GET_SERVICE_TRANSACTION_DATA_RES',

    'GET_CONTRACT_DATA_REQ': 'GET_CONTRACT_DATA_REQ',
    'GET_CONTRACT_DATA_RES': 'GET_CONTRACT_DATA_RES',

    'GET_TAB_DATA_REQ': 'GET_TAB_DATA_REQ',
    'GET_TAB_DATA_RES': 'GET_TAB_DATA_RES',

    'GET_CUSTOMER_DASHBOARD_DATA_REQ': 'GET_CUSTOMER_DASHBOARD_DATA_REQ',
    'GET_CUSTOMER_DASHBOARD_DATA_RES': 'GET_CUSTOMER_DASHBOARD_DATA_RES',

    'GET_DEVICE_DATA_REQ': 'GET_DEVICE_DATA_REQ,',
    'GET_DEVICE_DATA_RES' : 'GET_DEVICE_DATA_RES',

    'GET_TOP_CONNECT_DATA_REQ': 'GET_TOP_CONNECT_DATA_REQ',
    'GET_TOP_CONNECT_DATA_RES': 'GET_TOP_CONNECT_DATA_RES',

    'GET_CHANNEL_INTERACTION_DATA_REQ': 'GET_CHANNEL_INTERACTION_DATA_REQ',
    'GET_CHANNEL_INTERACTION_DATA_RES': 'GET_CHANNEL_INTERACTION_DATA_RES',

    'GET_PREDICTION_CHART_DATA_REQ': 'GET_PREDICTION_CHART_DATA_REQ',
    'GET_PREDICTION_CHART_DATA_RES': 'GET_PREDICTION_CHART_DATA_RES',

    'GET_NEXT_BASED_ACTION_REQ': 'GET_NEXT_BASED_ACTION_REQ',
    'GET_NEXT_BASED_ACTION_RES': 'GET_NEXT_BASED_ACTION_RES'

}