"use strict";
exports.__esModule = true;
var customer_1 = require("./customer");
var item_1 = require("./item");
var order_1 = require("./order");
var orderitem_1 = require("./orderitem");
var regcust_1 = require("./regcust");
var restaurants_1 = require("./restaurants");
var restaurants1 = new restaurants_1.Restaurants("zemato");
var item1 = new item_1.Item(500, "north indian");
var item2 = new item_1.Item(1000, "south indian");
var item3 = new item_1.Item(200, "drinks");
var item4 = new item_1.Item(100, "sweets");
restaurants1.item.push(item1);
restaurants1.item.push(item2);
restaurants1.item.push(item3);
restaurants1.item.push(item4);
var orderItem1 = new orderitem_1.Orderitem(3, [item1]);
var orderItem2 = new orderitem_1.Orderitem(4, [item2]);
var orderItem3 = new orderitem_1.Orderitem(4, [item3]);
var orderItem4 = new orderitem_1.Orderitem(5, [item4]);
var order1 = new order_1.Order();
var order2 = new order_1.Order();
order1.orderItem.push(orderItem1);
order1.orderItem.push(orderItem2);
order2.orderItem.push(orderItem3);
order2.orderItem.push(orderItem4);
var customer1 = new customer_1.Customer("Shaurya");
var regCustomer1 = new regcust_1.RegCustomer("Arjun", 10);
customer1.order.push(order1);
regCustomer1.order.push(order2);
restaurants1.customer.push(customer1);
restaurants1.customer.push(regCustomer1);
console.log("Restaurant name:" + ("" + restaurants1.getName()));
console.log("customer name:" + ("" + customer1.getName()));
console.log("customer id:" + ("" + customer1.getCustomerId()));
console.log("Order Id is" + ("" + order1.getOrderId()));
console.log("Ordered quantity" + ("" + orderItem1.getQuantity()));
console.log("Ordered quantity" + ("" + orderItem2.getQuantity()));
console.log("Description:" + ("" + item1.getDescription()));
console.log("Description:" + ("" + item2.getDescription()));
console.log("Price:" + ("" + item1.getPrice()));
console.log("Price:" + ("" + item2.getPrice()));
console.log("Networth of the restaurant:" + ("" + restaurants1.getTotalOrderWorth()));
