/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyCard {
        "tutorialName": string;
    }
    interface StencilLifecycle {
        "tutorialName": string;
    }
}
declare global {
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLStencilLifecycleElement extends Components.StencilLifecycle, HTMLStencilElement {
    }
    var HTMLStencilLifecycleElement: {
        prototype: HTMLStencilLifecycleElement;
        new (): HTMLStencilLifecycleElement;
    };
    interface HTMLElementTagNameMap {
        "my-card": HTMLMyCardElement;
        "stencil-lifecycle": HTMLStencilLifecycleElement;
    }
}
declare namespace LocalJSX {
    interface MyCard {
        "tutorialName"?: string;
    }
    interface StencilLifecycle {
        "tutorialName"?: string;
    }
    interface IntrinsicElements {
        "my-card": MyCard;
        "stencil-lifecycle": StencilLifecycle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "stencil-lifecycle": LocalJSX.StencilLifecycle & JSXBase.HTMLAttributes<HTMLStencilLifecycleElement>;
        }
    }
}
